services:

  db:

    image: postgres
    restart: always
    
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user
    
    networks:
      - my-network
    
    container_name: postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      timeout: 20s
      retries: 10

  mypythonapp:
    
    build: ./
    container_name: mypyapp
    networks:
      - my-network
    depends_on:
      db:
        condition: service_healthy
    stdin_open: true
    tty: true

networks:
  my-network: